name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Install dependencies
        run: make install

      - name: Lint with pylint
        run: make lint

      - name: Format code
        run: make format

      - name: Add Hugging Face remote
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          git remote add space https://huggingface.co/spaces/Danyal110/demo2

      - name: Push to Hugging Face
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git push --force https://Danyal110:${HF_TOKEN}@huggingface.co/spaces/Danyal110/demo2 HEAD:main
